[2025-03-27T12:19:19.865+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T12:19:19.885+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.add_rockets_to_table manual__2025-03-27T12:18:35.510549+00:00 [queued]>
[2025-03-27T12:19:19.893+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.add_rockets_to_table manual__2025-03-27T12:18:35.510549+00:00 [queued]>
[2025-03-27T12:19:19.893+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-27T12:19:19.908+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): add_rockets_to_table> on 2025-03-27 12:18:35.510549+00:00
[2025-03-27T12:19:19.916+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=576) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-27T12:19:19.918+0000] {standard_task_runner.py:72} INFO - Started process 578 to run task
[2025-03-27T12:19:19.918+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'add_rockets_to_table', 'manual__2025-03-27T12:18:35.510549+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp7itj24ml']
[2025-03-27T12:19:19.919+0000] {standard_task_runner.py:105} INFO - Job 67: Subtask add_rockets_to_table
[2025-03-27T12:19:20.155+0000] {task_command.py:467} INFO - Running <TaskInstance: my_dag.add_rockets_to_table manual__2025-03-27T12:18:35.510549+00:00 [running]> on host 2753c0b03e32
[2025-03-27T12:19:20.216+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='add_rockets_to_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T12:18:35.510549+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-27T12:18:35.510549+00:00'
[2025-03-27T12:19:20.216+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-27T12:19:20.217+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-27T12:19:20.217+0000] {logging_mixin.py:190} INFO - Current task name:add_rockets_to_table state:running start_date:2025-03-27 12:19:19.885445+00:00
[2025-03-27T12:19:20.217+0000] {logging_mixin.py:190} INFO - Dag name:my_dag and current dag run status:running
[2025-03-27T12:19:20.218+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-27T12:19:20.225+0000] {base.py:84} INFO - Retrieving connection 'postgres_db'
[2025-03-27T12:19:22.795+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: can't adapt type 'dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/airflow/dags/main_dag.py", line 24, in load_data
    session.commit()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1454, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 832, in commit
    self._prepare_impl()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 811, in _prepare_impl
    self.session.flush()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3588, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
    c = connection._execute_20(
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'dict'
[SQL: INSERT INTO rockets (height, diameter, mass, first_stage, second_stage, engines, landing_legs, payload_weights, flickr_images, name, type, active, stages, boosters, cost_per_launch, success_rate_pct, first_flight, country, company, wikipedia, description, id) VALUES (%(height)s, %(diameter)s, %(mass)s, %(first_stage)s, %(second_stage)s, %(engines)s, %(landing_legs)s, %(payload_weights)s::VARCHAR[], %(flickr_images)s::VARCHAR[], %(name)s, %(type)s, %(active)s, %(stages)s, %(boosters)s, %(cost_per_launch)s, %(success_rate_pct)s, %(first_flight)s, %(country)s, %(company)s, %(wikipedia)s, %(description)s, %(id)s)]
[parameters: {'height': '{"meters": 22.25, "feet": 73}', 'diameter': '{"meters": 1.68, "feet": 5.5}', 'mass': '{"kg": 30146, "lb": 66460}', 'first_stage': '{"thrust_sea_level": {"kN": 420, "lbf": 94000}, "thrust_vacuum": {"kN": 480, "lbf": 110000}, "reusable": false, "engines": 1, "fuel_amount_tons": 44.3, "burn_time_sec": 169}', 'second_stage': '{"thrust": {"kN": 31, "lbf": 7000}, "payloads": {"composite_fairing": {"height": {"meters": 3.5, "feet": 11.5}, "diameter": {"meters": 1.5, "feet": 4.9}}, "option_1": "composite fairing"}, "reusable": false, "engines": 1, "fuel_amount_tons": 3.38, "burn_time_sec": 378}', 'engines': '{"isp": {"sea_level": 267, "vacuum": 304}, "thrust_sea_level": {"kN": 420, "lbf": 94000}, "thrust_vacuum": {"kN": 480, "lbf": 110000}, "number": 1, " ... (16 characters truncated) ...  "version": "1C", "layout": "single", "engine_loss_max": 0, "propellant_1": "liquid oxygen", "propellant_2": "RP-1 kerosene", "thrust_to_weight": 96}', 'landing_legs': '{"number": 0, "material": null}', 'payload_weights': [{'id': 'leo', 'name': 'Low Earth Orbit', 'kg': 450, 'lb': 992}], 'flickr_images': ['https://imgur.com/DaCfMsj.jpg', 'https://imgur.com/azYafd8.jpg'], 'name': 'Falcon 1', 'type': 'rocket', 'active': False, 'stages': 2, 'boosters': 0, 'cost_per_launch': 6700000, 'success_rate_pct': 40, 'first_flight': '2006-03-24', 'country': 'Republic of the Marshall Islands', 'company': 'SpaceX', 'wikipedia': 'https://en.wikipedia.org/wiki/Falcon_1', 'description': 'The Falcon 1 was an expendable launch system privately developed and manufactured by SpaceX during 2006-2009. On 28 September 2008, Falcon 1 became the first privately-developed liquid-fuel launch vehicle to go into orbit around the Earth.', 'id': '5e9d0d95eda69955f709d1eb'}]
(Background on this error at: https://sqlalche.me/e/14/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main_dag.py", line 29, in load_data
    raise Exception(f"Ошикбка {e}")
Exception: Ошикбка (psycopg2.ProgrammingError) can't adapt type 'dict'
[SQL: INSERT INTO rockets (height, diameter, mass, first_stage, second_stage, engines, landing_legs, payload_weights, flickr_images, name, type, active, stages, boosters, cost_per_launch, success_rate_pct, first_flight, country, company, wikipedia, description, id) VALUES (%(height)s, %(diameter)s, %(mass)s, %(first_stage)s, %(second_stage)s, %(engines)s, %(landing_legs)s, %(payload_weights)s::VARCHAR[], %(flickr_images)s::VARCHAR[], %(name)s, %(type)s, %(active)s, %(stages)s, %(boosters)s, %(cost_per_launch)s, %(success_rate_pct)s, %(first_flight)s, %(country)s, %(company)s, %(wikipedia)s, %(description)s, %(id)s)]
[parameters: {'height': '{"meters": 22.25, "feet": 73}', 'diameter': '{"meters": 1.68, "feet": 5.5}', 'mass': '{"kg": 30146, "lb": 66460}', 'first_stage': '{"thrust_sea_level": {"kN": 420, "lbf": 94000}, "thrust_vacuum": {"kN": 480, "lbf": 110000}, "reusable": false, "engines": 1, "fuel_amount_tons": 44.3, "burn_time_sec": 169}', 'second_stage': '{"thrust": {"kN": 31, "lbf": 7000}, "payloads": {"composite_fairing": {"height": {"meters": 3.5, "feet": 11.5}, "diameter": {"meters": 1.5, "feet": 4.9}}, "option_1": "composite fairing"}, "reusable": false, "engines": 1, "fuel_amount_tons": 3.38, "burn_time_sec": 378}', 'engines': '{"isp": {"sea_level": 267, "vacuum": 304}, "thrust_sea_level": {"kN": 420, "lbf": 94000}, "thrust_vacuum": {"kN": 480, "lbf": 110000}, "number": 1, " ... (16 characters truncated) ...  "version": "1C", "layout": "single", "engine_loss_max": 0, "propellant_1": "liquid oxygen", "propellant_2": "RP-1 kerosene", "thrust_to_weight": 96}', 'landing_legs': '{"number": 0, "material": null}', 'payload_weights': [{'id': 'leo', 'name': 'Low Earth Orbit', 'kg': 450, 'lb': 992}], 'flickr_images': ['https://imgur.com/DaCfMsj.jpg', 'https://imgur.com/azYafd8.jpg'], 'name': 'Falcon 1', 'type': 'rocket', 'active': False, 'stages': 2, 'boosters': 0, 'cost_per_launch': 6700000, 'success_rate_pct': 40, 'first_flight': '2006-03-24', 'country': 'Republic of the Marshall Islands', 'company': 'SpaceX', 'wikipedia': 'https://en.wikipedia.org/wiki/Falcon_1', 'description': 'The Falcon 1 was an expendable launch system privately developed and manufactured by SpaceX during 2006-2009. On 28 September 2008, Falcon 1 became the first privately-developed liquid-fuel launch vehicle to go into orbit around the Earth.', 'id': '5e9d0d95eda69955f709d1eb'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-03-27T12:19:22.810+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-27T12:19:22.811+0000] {logging_mixin.py:190} INFO - Task start:2025-03-27 12:19:19.885445+00:00 end:2025-03-27 12:19:22.810331+00:00 duration:2.924886
[2025-03-27T12:19:22.811+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): add_rockets_to_table> dag:<DAG: my_dag> dagrun:<DagRun my_dag @ 2025-03-27 12:18:35.510549+00:00: manual__2025-03-27T12:18:35.510549+00:00, state:running, queued_at: 2025-03-27 12:18:35.519163+00:00. externally triggered: True>
[2025-03-27T12:19:22.811+0000] {logging_mixin.py:190} INFO - Failure caused by Ошикбка (psycopg2.ProgrammingError) can't adapt type 'dict'
[SQL: INSERT INTO rockets (height, diameter, mass, first_stage, second_stage, engines, landing_legs, payload_weights, flickr_images, name, type, active, stages, boosters, cost_per_launch, success_rate_pct, first_flight, country, company, wikipedia, description, id) VALUES (%(height)s, %(diameter)s, %(mass)s, %(first_stage)s, %(second_stage)s, %(engines)s, %(landing_legs)s, %(payload_weights)s::VARCHAR[], %(flickr_images)s::VARCHAR[], %(name)s, %(type)s, %(active)s, %(stages)s, %(boosters)s, %(cost_per_launch)s, %(success_rate_pct)s, %(first_flight)s, %(country)s, %(company)s, %(wikipedia)s, %(description)s, %(id)s)]
[parameters: {'height': '{"meters": 22.25, "feet": 73}', 'diameter': '{"meters": 1.68, "feet": 5.5}', 'mass': '{"kg": 30146, "lb": 66460}', 'first_stage': '{"thrust_sea_level": {"kN": 420, "lbf": 94000}, "thrust_vacuum": {"kN": 480, "lbf": 110000}, "reusable": false, "engines": 1, "fuel_amount_tons": 44.3, "burn_time_sec": 169}', 'second_stage': '{"thrust": {"kN": 31, "lbf": 7000}, "payloads": {"composite_fairing": {"height": {"meters": 3.5, "feet": 11.5}, "diameter": {"meters": 1.5, "feet": 4.9}}, "option_1": "composite fairing"}, "reusable": false, "engines": 1, "fuel_amount_tons": 3.38, "burn_time_sec": 378}', 'engines': '{"isp": {"sea_level": 267, "vacuum": 304}, "thrust_sea_level": {"kN": 420, "lbf": 94000}, "thrust_vacuum": {"kN": 480, "lbf": 110000}, "number": 1, " ... (16 characters truncated) ...  "version": "1C", "layout": "single", "engine_loss_max": 0, "propellant_1": "liquid oxygen", "propellant_2": "RP-1 kerosene", "thrust_to_weight": 96}', 'landing_legs': '{"number": 0, "material": null}', 'payload_weights': [{'id': 'leo', 'name': 'Low Earth Orbit', 'kg': 450, 'lb': 992}], 'flickr_images': ['https://imgur.com/DaCfMsj.jpg', 'https://imgur.com/azYafd8.jpg'], 'name': 'Falcon 1', 'type': 'rocket', 'active': False, 'stages': 2, 'boosters': 0, 'cost_per_launch': 6700000, 'success_rate_pct': 40, 'first_flight': '2006-03-24', 'country': 'Republic of the Marshall Islands', 'company': 'SpaceX', 'wikipedia': 'https://en.wikipedia.org/wiki/Falcon_1', 'description': 'The Falcon 1 was an expendable launch system privately developed and manufactured by SpaceX during 2006-2009. On 28 September 2008, Falcon 1 became the first privately-developed liquid-fuel launch vehicle to go into orbit around the Earth.', 'id': '5e9d0d95eda69955f709d1eb'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-03-27T12:19:22.812+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=my_dag, task_id=add_rockets_to_table, run_id=manual__2025-03-27T12:18:35.510549+00:00, execution_date=20250327T121835, start_date=20250327T121919, end_date=20250327T121922
[2025-03-27T12:19:22.842+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-27T12:19:22.842+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 67 for task add_rockets_to_table (Ошикбка (psycopg2.ProgrammingError) can't adapt type 'dict'
[SQL: INSERT INTO rockets (height, diameter, mass, first_stage, second_stage, engines, landing_legs, payload_weights, flickr_images, name, type, active, stages, boosters, cost_per_launch, success_rate_pct, first_flight, country, company, wikipedia, description, id) VALUES (%(height)s, %(diameter)s, %(mass)s, %(first_stage)s, %(second_stage)s, %(engines)s, %(landing_legs)s, %(payload_weights)s::VARCHAR[], %(flickr_images)s::VARCHAR[], %(name)s, %(type)s, %(active)s, %(stages)s, %(boosters)s, %(cost_per_launch)s, %(success_rate_pct)s, %(first_flight)s, %(country)s, %(company)s, %(wikipedia)s, %(description)s, %(id)s)]
[parameters: {'height': '{"meters": 22.25, "feet": 73}', 'diameter': '{"meters": 1.68, "feet": 5.5}', 'mass': '{"kg": 30146, "lb": 66460}', 'first_stage': '{"thrust_sea_level": {"kN": 420, "lbf": 94000}, "thrust_vacuum": {"kN": 480, "lbf": 110000}, "reusable": false, "engines": 1, "fuel_amount_tons": 44.3, "burn_time_sec": 169}', 'second_stage': '{"thrust": {"kN": 31, "lbf": 7000}, "payloads": {"composite_fairing": {"height": {"meters": 3.5, "feet": 11.5}, "diameter": {"meters": 1.5, "feet": 4.9}}, "option_1": "composite fairing"}, "reusable": false, "engines": 1, "fuel_amount_tons": 3.38, "burn_time_sec": 378}', 'engines': '{"isp": {"sea_level": 267, "vacuum": 304}, "thrust_sea_level": {"kN": 420, "lbf": 94000}, "thrust_vacuum": {"kN": 480, "lbf": 110000}, "number": 1, " ... (16 characters truncated) ...  "version": "1C", "layout": "single", "engine_loss_max": 0, "propellant_1": "liquid oxygen", "propellant_2": "RP-1 kerosene", "thrust_to_weight": 96}', 'landing_legs': '{"number": 0, "material": null}', 'payload_weights': [{'id': 'leo', 'name': 'Low Earth Orbit', 'kg': 450, 'lb': 992}], 'flickr_images': ['https://imgur.com/DaCfMsj.jpg', 'https://imgur.com/azYafd8.jpg'], 'name': 'Falcon 1', 'type': 'rocket', 'active': False, 'stages': 2, 'boosters': 0, 'cost_per_launch': 6700000, 'success_rate_pct': 40, 'first_flight': '2006-03-24', 'country': 'Republic of the Marshall Islands', 'company': 'SpaceX', 'wikipedia': 'https://en.wikipedia.org/wiki/Falcon_1', 'description': 'The Falcon 1 was an expendable launch system privately developed and manufactured by SpaceX during 2006-2009. On 28 September 2008, Falcon 1 became the first privately-developed liquid-fuel launch vehicle to go into orbit around the Earth.', 'id': '5e9d0d95eda69955f709d1eb'}]
(Background on this error at: https://sqlalche.me/e/14/f405); 578)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: can't adapt type 'dict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/airflow/dags/main_dag.py", line 24, in load_data
    session.commit()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1454, in commit
    self._transaction.commit(_to_root=self.future)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 832, in commit
    self._prepare_impl()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 811, in _prepare_impl
    self.session.flush()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3449, in flush
    self._flush(objects)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3588, in _flush
    with util.safe_reraise():
         ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3549, in _flush
    flush_context.execute()
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    _emit_insert_statements(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1097, in _emit_insert_statements
    c = connection._execute_20(
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) can't adapt type 'dict'
[SQL: INSERT INTO rockets (height, diameter, mass, first_stage, second_stage, engines, landing_legs, payload_weights, flickr_images, name, type, active, stages, boosters, cost_per_launch, success_rate_pct, first_flight, country, company, wikipedia, description, id) VALUES (%(height)s, %(diameter)s, %(mass)s, %(first_stage)s, %(second_stage)s, %(engines)s, %(landing_legs)s, %(payload_weights)s::VARCHAR[], %(flickr_images)s::VARCHAR[], %(name)s, %(type)s, %(active)s, %(stages)s, %(boosters)s, %(cost_per_launch)s, %(success_rate_pct)s, %(first_flight)s, %(country)s, %(company)s, %(wikipedia)s, %(description)s, %(id)s)]
[parameters: {'height': '{"meters": 22.25, "feet": 73}', 'diameter': '{"meters": 1.68, "feet": 5.5}', 'mass': '{"kg": 30146, "lb": 66460}', 'first_stage': '{"thrust_sea_level": {"kN": 420, "lbf": 94000}, "thrust_vacuum": {"kN": 480, "lbf": 110000}, "reusable": false, "engines": 1, "fuel_amount_tons": 44.3, "burn_time_sec": 169}', 'second_stage': '{"thrust": {"kN": 31, "lbf": 7000}, "payloads": {"composite_fairing": {"height": {"meters": 3.5, "feet": 11.5}, "diameter": {"meters": 1.5, "feet": 4.9}}, "option_1": "composite fairing"}, "reusable": false, "engines": 1, "fuel_amount_tons": 3.38, "burn_time_sec": 378}', 'engines': '{"isp": {"sea_level": 267, "vacuum": 304}, "thrust_sea_level": {"kN": 420, "lbf": 94000}, "thrust_vacuum": {"kN": 480, "lbf": 110000}, "number": 1, " ... (16 characters truncated) ...  "version": "1C", "layout": "single", "engine_loss_max": 0, "propellant_1": "liquid oxygen", "propellant_2": "RP-1 kerosene", "thrust_to_weight": 96}', 'landing_legs': '{"number": 0, "material": null}', 'payload_weights': [{'id': 'leo', 'name': 'Low Earth Orbit', 'kg': 450, 'lb': 992}], 'flickr_images': ['https://imgur.com/DaCfMsj.jpg', 'https://imgur.com/azYafd8.jpg'], 'name': 'Falcon 1', 'type': 'rocket', 'active': False, 'stages': 2, 'boosters': 0, 'cost_per_launch': 6700000, 'success_rate_pct': 40, 'first_flight': '2006-03-24', 'country': 'Republic of the Marshall Islands', 'company': 'SpaceX', 'wikipedia': 'https://en.wikipedia.org/wiki/Falcon_1', 'description': 'The Falcon 1 was an expendable launch system privately developed and manufactured by SpaceX during 2006-2009. On 28 September 2008, Falcon 1 became the first privately-developed liquid-fuel launch vehicle to go into orbit around the Earth.', 'id': '5e9d0d95eda69955f709d1eb'}]
(Background on this error at: https://sqlalche.me/e/14/f405)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/main_dag.py", line 29, in load_data
    raise Exception(f"Ошикбка {e}")
Exception: Ошикбка (psycopg2.ProgrammingError) can't adapt type 'dict'
[SQL: INSERT INTO rockets (height, diameter, mass, first_stage, second_stage, engines, landing_legs, payload_weights, flickr_images, name, type, active, stages, boosters, cost_per_launch, success_rate_pct, first_flight, country, company, wikipedia, description, id) VALUES (%(height)s, %(diameter)s, %(mass)s, %(first_stage)s, %(second_stage)s, %(engines)s, %(landing_legs)s, %(payload_weights)s::VARCHAR[], %(flickr_images)s::VARCHAR[], %(name)s, %(type)s, %(active)s, %(stages)s, %(boosters)s, %(cost_per_launch)s, %(success_rate_pct)s, %(first_flight)s, %(country)s, %(company)s, %(wikipedia)s, %(description)s, %(id)s)]
[parameters: {'height': '{"meters": 22.25, "feet": 73}', 'diameter': '{"meters": 1.68, "feet": 5.5}', 'mass': '{"kg": 30146, "lb": 66460}', 'first_stage': '{"thrust_sea_level": {"kN": 420, "lbf": 94000}, "thrust_vacuum": {"kN": 480, "lbf": 110000}, "reusable": false, "engines": 1, "fuel_amount_tons": 44.3, "burn_time_sec": 169}', 'second_stage': '{"thrust": {"kN": 31, "lbf": 7000}, "payloads": {"composite_fairing": {"height": {"meters": 3.5, "feet": 11.5}, "diameter": {"meters": 1.5, "feet": 4.9}}, "option_1": "composite fairing"}, "reusable": false, "engines": 1, "fuel_amount_tons": 3.38, "burn_time_sec": 378}', 'engines': '{"isp": {"sea_level": 267, "vacuum": 304}, "thrust_sea_level": {"kN": 420, "lbf": 94000}, "thrust_vacuum": {"kN": 480, "lbf": 110000}, "number": 1, " ... (16 characters truncated) ...  "version": "1C", "layout": "single", "engine_loss_max": 0, "propellant_1": "liquid oxygen", "propellant_2": "RP-1 kerosene", "thrust_to_weight": 96}', 'landing_legs': '{"number": 0, "material": null}', 'payload_weights': [{'id': 'leo', 'name': 'Low Earth Orbit', 'kg': 450, 'lb': 992}], 'flickr_images': ['https://imgur.com/DaCfMsj.jpg', 'https://imgur.com/azYafd8.jpg'], 'name': 'Falcon 1', 'type': 'rocket', 'active': False, 'stages': 2, 'boosters': 0, 'cost_per_launch': 6700000, 'success_rate_pct': 40, 'first_flight': '2006-03-24', 'country': 'Republic of the Marshall Islands', 'company': 'SpaceX', 'wikipedia': 'https://en.wikipedia.org/wiki/Falcon_1', 'description': 'The Falcon 1 was an expendable launch system privately developed and manufactured by SpaceX during 2006-2009. On 28 September 2008, Falcon 1 became the first privately-developed liquid-fuel launch vehicle to go into orbit around the Earth.', 'id': '5e9d0d95eda69955f709d1eb'}]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2025-03-27T12:19:22.886+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-27T12:19:23.070+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-27T12:19:23.081+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
